### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by eukaryote31** [pRizz/iota-transaction-spammer-webapp#10]
Maybe an embedded version would be nice, so iota-related site owners can embed it in their sites and make their visitors help the iota network! Obviously, opt-out cookies and zero performance impact are a must.

**Comment by pRizz** [comment]
An embedded version is already possible if you look at the dependency https://github.com/pRizz/iota.transactionSpammer.js
There are some basic instructions for adding this to a website
