### ISSUE TITLE
Spamming broken; update to latest iota.lib.js

### ISSUE THREAD

**Issue by pRizz** [pRizz/iota-transaction-spammer-webapp#22]

**Comment by extrax** [comment]
seems like replacing the library with the newest version is enough to make the spammer work again

**Comment by mrstormlars** [comment]
From https://iota.stackexchange.com/questions/1256/im-running-a-full-node-how-can-i-help-speed-up-other-peoples-transactions:
"maybe you have to update to the latest iota.lib.js v0.4.6. i think that spammer app still uses a old one"

**Comment by pRizz** [comment]
Updated to latest 0.4.6
