### ISSUE TITLE
2017-11-10T19:37:47.237Z: Error getting tips.

### ISSUE THREAD

**Issue by wonkytonky** [pRizz/iota-transaction-spammer-webapp#25]
2017-11-10T19:37:47.237Z: Error getting tips.
2017-11-10T19:37:47.066Z: Getting tip transactions... This may take a while...

**Comment by pRizz** [comment]
Can you please provide more details? What browser, what node, etc.

**Comment by wonkytonky** [comment]
https://normpad.github.io/IOTA-Reattacher/ the link i use

![image](https://user-images.githubusercontent.com/19390834/32679084-5d33a33e-c665-11e7-9397-93b9f74a82be.png)


chrome 62.0.3202.89 (Official build) (64-bits)

**Comment by pRizz** [comment]
This is the incorrect repository. Please post your issue there https://github.com/normpad/IOTA-Reattacher/issues

**Comment by pRizz** [comment]
Also, that node seems to be unreliable
