### ISSUE TITLE
webapp doesnt allow HTTP nodes (only HTTPS)

### ISSUE THREAD

**Issue by rafaelbrizola** [pRizz/iota-transaction-spammer-webapp#29]
The webapp doesnt allow to add a http (not HTTPS) host in the settings. It only accepts HTTPS. When cloning the repository and running it locally, it works normally.

**Comment by pRizz** [comment]
This is a web browser feature. You cannot access http endpoints if you are on an https site. I have an http mirror here http://prizziota.com/iota-transaction-spammer-webapp/index.html
