### ISSUE TITLE
Transactions not confirmed after spamming.

### ISSUE THREAD

**Issue by berrytchaks** [pRizz/iota-transaction-spammer-webapp#31]
I have setup a private testnet using https://github.com/schierlm/private-iota-testnet. My goals is to confirm all transactions that are done on this testnet. So I cloned this spammer-webapp and added the ip address of my testnet as the ONLY provider in the file https://github.com/pRizz/iota.transactionSpammer.js/blob/4621bb57bd07a30df6ada8fd4d6019a11eb39f42/src/transactionSpammer.js. I then launched the project on my browser and clicked on start spamming but none of the transactions that I did got confirmed despite the fact that the browser says 16 transactions confirmed. I'd believe I'm missing something but I don't know where to search. 
Any clues? 
Thanks.

**Comment by pRizz** [comment]
I realize my language is a bit misleading. I should have named "confirmed" as "approved". Only IOTA's coordinator has the authority to "confirm", afaik.

**Comment by berrytchaks** [comment]
Ok, thanks for the clarification.
