### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by agus-xyz** [pRizz/iota-transaction-spammer-webapp#6]
![untitled](https://user-images.githubusercontent.com/3696240/30265344-2ca043ac-96dc-11e7-99ef-42abd96ff106.png)

Best.

**Comment by pRizz** [comment]
The two node operators have blocked access from this webapp due to network issues. Try running the webapp locally by downloading the repo and opening index.html

**Comment by agus-xyz** [comment]
when downloading the source and opening index.html my event log window is absolutely empty. 
Best and thanks!

**Comment by wonkytonky** [comment]
look at dependencies..  you have to download another zip

**Comment by pRizz** [comment]
I made a release which includes all needed files: https://github.com/pRizz/iota-transaction-spammer-webapp/releases/download/1.0/iota-transaction-spammer-webapp.zip

**Comment by agus-xyz** [comment]
Thanks! Working.
