### ISSUE TITLE
more nodes

### ISSUE THREAD

**Issue by wonkytonky** [pRizz/iota-transaction-spammer-webapp#7]
can you please add more nodes on the website .. 
both are not synced.. it seems so the spammer  keeps reconnecting to 2 nodes which never work then.

**Comment by pRizz** [comment]
I just added http nodes, so you can hit them if you clone/download the repo and run index.html locally. As long as this webapp is hosted over GitHub Pages, I can only hit the two https nodes that I know of.

**Comment by wonkytonky** [comment]
hi, thansk for the quick response .

request: maybe a dropdown where one can choose or manutally add a node (like in light wallet ) i can do it myself in code . but i'm sure lots of noncoders would love this option.  this way the network load is spread over more nodes aswell.

**Comment by pRizz** [comment]
@wonkytonky Yep, I do have a "Settings page" in my to-do list :+1:

**Comment by pRizz** [comment]
Added settings in 623289fa389065289b0e95b86323d760661c4986
